
(function(){
function copy(text,btn){navigator.clipboard?.writeText(text).then(()=>{if(btn){btn.textContent='Copied ✓'; setTimeout(()=>btn.textContent=btn.dataset.label||'Copy',1600)}})}
function stackNames(){return [...document.querySelectorAll('#stackShareCard li')].map(li=>li.textContent.trim()).filter(Boolean)}
function stackTitle(){return document.querySelector('#stackShareCard h2')?.textContent.trim()||'My AI stack'}
function shareText(kind){const names=stackNames().join(' + '); const url=location.href; const title=stackTitle(); if(kind==='linkedin') return `I generated ${title}: ${names}. Built with AIToolsEssentials: ${url}`; if(kind==='reddit') return `I tried this AI stack generator and got: ${names}. What would you swap? ${url}`; if(kind==='email') return `Subject: AI stack idea\n\nI generated this AI stack: ${names}\n\nYou can customize it here: ${url}`; return `My AI stack: ${names}\nGenerate yours: ${url}`}
function scoreStack(){const card=document.getElementById('stackShareCard'); const host=document.getElementById('stackResult'); if(!card||!host||document.getElementById('stackScore'))return; const names=stackNames(); const cats=[...document.querySelectorAll('#stackResult .content-hub-card > span')].map(x=>x.textContent.split('·')[0].trim()); const unique=new Set(cats); const free=[...document.querySelectorAll('#stackResult .content-hub-card > span')].filter(x=>/free/i.test(x.textContent)).length; const score=Math.min(96,60+unique.size*7+free*3); const gaps=['Research','Automation','Creative','Meetings','Development'].filter(g=>![...unique].some(c=>c.toLowerCase().includes(g.toLowerCase()))); const html=`<div class="stack-score" id="stackScore"><span>AI Stack Score</span><strong>${score}/100</strong><p>Coverage: ${unique.size} categories · Free-first tools: ${free}/${names.length}</p><p>${gaps.length?'Possible gaps: '+gaps.join(', '):'Strong coverage across common workflows.'}</p></div>`; card.insertAdjacentHTML('afterend',html)}
function addShareCopyButtons(){const host=document.getElementById('stackResult'); if(!host||document.getElementById('shareCopyPanel'))return; const panel=document.createElement('div'); panel.className='share-copy-panel'; panel.id='shareCopyPanel'; panel.innerHTML='<span>Copy launch-ready share text</span><button class="button button-blue small" data-kind="x" data-label="Copy X post">Copy X post</button><button class="button button-blue small" data-kind="linkedin" data-label="Copy LinkedIn post">Copy LinkedIn post</button><button class="button button-blue small" data-kind="reddit" data-label="Copy Reddit post">Copy Reddit post</button><button class="button button-blue small" data-kind="email" data-label="Copy email">Copy email</button>'; host.appendChild(panel); panel.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>copy(shareText(b.dataset.kind),b)))}
function addFreeAlternatives(){if(!window.COST_TOOLS||!document.getElementById('costSummary')||document.getElementById('freeAltPanel'))return; const free=COST_TOOLS.filter(t=>/free/i.test(t.price||'')).slice(0,6); const panel=document.createElement('div'); panel.className='score-card free-alt-panel'; panel.id='freeAltPanel'; panel.innerHTML=`<span>Lower-cost swaps</span><h2>Try free tiers before paid stack sprawl.</h2><p>These tools have free or self-hosted starting points and can reduce early subscription risk.</p><div class="content-hub-grid">${free.map(t=>`<article class="content-hub-card"><span>${t.category} · ${t.price||''}</span><h3><a href="/tools/${t.slug}/">${t.name}</a></h3><p>${t.summary||''}</p><a class="button button-blue small" href="/tools/${t.slug}/">Read review</a></article>`).join('')}</div>`; document.getElementById('costSummary').after(panel)}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{scoreStack();addShareCopyButtons();addFreeAlternatives()},50)});
})();
