#!/usr/bin/env python3
"""Generate source-linked how-to guides for local and agentic AI stacks."""
from pathlib import Path
from html import escape
import json

DOMAIN='https://aitoolsessentials.com'
GUIDES=[
{"slug":"install-hermes-agent","title":"How to install and configure Hermes Agent safely","summary":"A source-led setup path for installing Hermes Agent, choosing a provider, isolating profiles, and testing tools before connecting messaging or automation.","tool":"Hermes Agent","sources":[("Hermes documentation","https://hermes-agent.nousresearch.com/docs/"),("Configuration","https://hermes-agent.nousresearch.com/docs/user-guide/configuration"),("Security","https://hermes-agent.nousresearch.com/docs/user-guide/security")],"steps":[("Start from the official documentation","Use the Hermes documentation and repository links as the source of truth. Check current platform support and installation instructions before running a command."),("Install and run setup","Use the documented setup flow to choose a provider and confirm the agent starts. Keep credentials in the supported secret store; never commit them to a project."),("Create a least-privilege profile","Use a separate profile for experiments. Start with the smallest toolset and no sensitive workspace so you can observe what the agent can read, write, execute, and send."),("Test one read-only workflow","Run a research or documentation task first. Record tool calls, source quality, latency, and whether the output is reproducible."),("Add capabilities one at a time","Enable terminal, browser, MCP, messaging, cron, or delegation only after the previous capability is understood. Review approvals and isolation settings before enabling actions."),("Create a reset and exit plan","Document the profile location, provider, enabled tools, scheduled jobs, and how to revoke credentials and remove the profile.")],"check":["Provider and model recorded","Experimental profile isolated","Tool permissions reviewed","No secrets in repository","Read-only task completed","Reset path documented"]},
{"slug":"run-openclaw-locally","title":"How to run OpenClaw locally without losing control","summary":"A contained OpenClaw pilot that starts with one channel, one model provider, and no high-risk tools before expanding the gateway.","tool":"OpenClaw","sources":[("OpenClaw documentation","https://docs.openclaw.ai/"),("OpenClaw license","https://github.com/openclaw/openclaw/blob/main/LICENSE")],"steps":[("Confirm the official project","Start from docs.openclaw.ai and follow its repository link. Similar project names can have different licenses and security properties."),("Choose the deployment boundary","Decide whether the gateway runs on a laptop, home server, VPS, or managed service. Write down network exposure, backup location, update owner, and expected model/hosting cost."),("Configure one provider","Use one model provider for the pilot and keep credentials outside source control. Record model name, token pricing, context limits, and data-retention terms."),("Connect one low-risk channel","Use a private test channel first. Do not expose an unauthenticated gateway to the public internet or connect personal accounts before access controls are verified."),("Run a bounded task","Give the agent one repeatable task with no destructive tools. Inspect logs, token usage, retries, extensions, and unexpected side effects."),("Expand only after the pilot","Add channels, skills, tools, and remote access one at a time. Keep a rollback copy and a written list of what can access personal data.")],"check":["Official repository confirmed","Deployment boundary documented","Provider costs recorded","Private test channel used","Gateway exposure reviewed","Rollback plan tested"]},
{"slug":"install-ollama-and-run-a-model","title":"How to install Ollama and run a local model","summary":"A repeatable Ollama quickstart that tests the local runtime, model license, hardware fit, and API before connecting other applications.","tool":"Ollama","sources":[("Ollama","https://ollama.com/"),("Quickstart","https://docs.ollama.com/quickstart"),("API introduction","https://docs.ollama.com/api/introduction"),("FAQ","https://docs.ollama.com/faq")],"steps":[("Install Ollama from the official source","Use the official download or installation instructions for your operating system. Avoid third-party installers that obscure the binary or model location."),("Choose a model deliberately","Read the model card and license before pulling it. Note parameter size, quantization, context length, capabilities, and hardware requirements."),("Run one interactive test","Pull and run the model, then send one fixed prompt from your real workflow. Record cold start, response quality, and whether the machine remains usable."),("Call the local API","Ollama documents a local API at localhost:11434 by default. Send the same prompt through the API and save response metadata without saving sensitive content."),("Measure the real cost","Record RAM/VRAM use, tokens per second, disk usage, energy/heat, context behavior, and model download time. Compare with one smaller model before buying hardware."),("Connect downstream tools carefully","After the local API is understood, connect Open WebUI, an editor, or an agent. Keep the API bound and authenticated according to current official guidance.")],"check":["Model license checked","Hardware requirement recorded","Cold start measured","Local API tested","Context behavior tested","Downstream connection documented"]},
{"slug":"connect-open-webui-to-ollama","title":"How to connect Open WebUI to Ollama","summary":"A practical local-stack setup: run Ollama as the model backend, deploy Open WebUI as the browser interface, and test privacy boundaries before adding documents or users.","tool":"Open WebUI","sources":[("Open WebUI docs","https://docs.openwebui.com/"),("Open WebUI quick start","https://docs.openwebui.com/getting-started/quick-start/"),("Open WebUI license","https://docs.openwebui.com/license/"),("Ollama API","https://docs.ollama.com/api/introduction")],"steps":[("Understand the two layers","Ollama runs or serves models; Open WebUI provides the browser interface and workflow layer. A problem in one layer can look like a problem in the other."),("Verify Ollama first","Run one model directly through Ollama before adding the UI. This gives you a known-good backend for troubleshooting."),("Deploy Open WebUI using the current official path","Follow the official quick-start instructions for Docker, Python, or Kubernetes. Pin and record the version used for the pilot."),("Connect the backend","Point Open WebUI at the Ollama endpoint using documented connection settings. Test model discovery and one short prompt before uploading documents."),("Test data boundaries","Use a synthetic document first. Check where chat history, uploaded files, embeddings, logs, backups, and admin credentials are stored."),("Add users and RAG after recovery testing","Test backup/restore, account separation, model permissions, and deletion behavior before confidential or team use.")],"check":["Ollama backend verified","Open WebUI version recorded","Connection tested","Synthetic document used","Storage locations mapped","Backup/restore tested"]},
{"slug":"secure-a-self-hosted-ai-agent","title":"How to secure a self-hosted AI agent before connecting real data","summary":"A provider-neutral security checklist for Hermes Agent, OpenClaw, and local model stacks before enabling tools, messaging, or confidential documents.","tool":"Hermes Agent","sources":[("Hermes security","https://hermes-agent.nousresearch.com/docs/user-guide/security"),("OpenClaw docs","https://docs.openclaw.ai/"),("Ollama FAQ","https://docs.ollama.com/faq"),("Open WebUI license","https://docs.openwebui.com/license/")],"steps":[("Map the trust boundary","List the model provider, agent runtime, UI, gateway, tools, extensions, storage, logs, backups, and every network path."),("Start with least privilege","Disable tools and channels you do not need. Use a separate user/profile and synthetic data for the first pilot."),("Protect credentials","Keep API keys and session tokens in the supported secret store. Never paste them into prompts, repositories, screenshots, issue reports, or public logs."),("Restrict network exposure","Keep local APIs and admin panels private until authentication, authorization, transport, and update procedures are verified."),("Review extensions and model terms","Treat skills, plugins, MCP servers, and downloaded models as supply-chain inputs. Check source, permissions, license, and update path."),("Test recovery and deletion","Prove you can revoke credentials, remove chat history/files, restore a clean backup, and shut down the agent without exposed services.")],"check":["Trust boundary mapped","Least privilege enabled","Secrets externalized","Network exposure restricted","Extensions reviewed","Recovery/deletion tested"]}
]

def e(x): return escape(str(x),quote=True)
def page(g):
    steps=''.join(f'<li><h2>{e(t)}</h2><p>{e(d)}</p></li>' for t,d in g['steps'])
    sources=''.join(f'<li><a href="{e(u)}" target="_blank" rel="external noopener">{e(n)} ↗</a></li>' for n,u in g['sources'])
    checks=''.join(f'<li>{e(x)}</li>' for x in g['check'])
    schema=json.dumps({'@context':'https://schema.org','@type':'HowTo','name':g['title'],'description':g['summary'],'url':f'{DOMAIN}/how-to/{g["slug"]}.html','step':[{'@type':'HowToStep','name':t,'text':d} for t,d in g['steps']]},separators=(',',':'))
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{e(g['summary'])}"><title>{e(g['title'])} | AIToolsEssentials</title><link rel="canonical" href="{DOMAIN}/how-to/{g['slug']}.html"><link rel="stylesheet" href="../css/styles.css"><link rel="stylesheet" href="../css/share.css"><script type="application/ld+json">{schema}</script></head><body><header class="global-nav"><a class="brand" href="../index.html"><span class="brand-glyph">✦</span><span>AIToolsEssentials</span></a><nav class="nav-links"><a href="../tools/index.html">Tools</a><a href="../fit-interview/">Fit interview</a><a href="../change-radar/">Change radar</a><a href="../articles/learn.html">Learn</a><a href="../pricing/">Premium</a></nav></header><main><section class="scene scene-dark"><div class="howto-hero"><p class="kicker">How-to · {e(g['tool'])}</p><h1>{e(g['title'])}</h1><p class="subhead">{e(g['summary'])}</p><p class="howto-disclaimer">Setup commands, limits, and security terms change. Follow the linked official documentation before running anything.</p></div></section><section class="scene scene-light"><article class="howto-article"><div class="howto-callout"><strong>Before you start</strong><p>Use a test profile, synthetic data, and no production credentials. This guide is strategy and evaluation guidance, not managed implementation or support.</p></div><ol class="howto-steps">{steps}</ol><section class="howto-check"><h2>Completion checklist</h2><ul>{checks}</ul></section><section class="howto-sources"><h2>Official sources</h2><ul>{sources}</ul></section><p class="howto-next"><a class="button button-blue" href="../tools/{e(g['tool'].lower().replace(' ','-'))}/">Review tool →</a><a class="button button-dark" href="../decision-brief.html">Create a decision brief</a></p></article></section></main><footer class="footer"><span>© 2026 AIToolsEssentials</span><a href="../methodology/">Methodology</a><a href="../legal/affiliate-disclosure.html">Affiliate disclosure</a><a href="../legal/privacy.html">Privacy</a><a href="../legal/terms.html">Terms</a></footer></body></html>'''

def generate(root:Path):
    out=root/'how-to'; out.mkdir(exist_ok=True)
    cards=[]
    for g in GUIDES:
        (out/f'{g["slug"]}.html').write_text(page(g))
        cards.append(f'<article class="content-hub-card"><span>How-to</span><h2><a href="{g["slug"]}.html">{e(g["title"])}</a></h2><p>{e(g["summary"])}</p></article>')
    hub=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Evidence-first how-to guides for Hermes Agent, OpenClaw, Ollama, Open WebUI, and self-hosted AI stacks."><title>AI Agent &amp; Local AI How-To Guides | AIToolsEssentials</title><link rel="canonical" href="{DOMAIN}/how-to/"><link rel="stylesheet" href="../css/styles.css"><link rel="stylesheet" href="../css/share.css"></head><body><header class="global-nav"><a class="brand" href="../index.html">✦ AIToolsEssentials</a><nav class="nav-links"><a href="../tools/index.html">Tools</a><a href="../fit-interview/">Fit interview</a><a href="../change-radar/">Change radar</a><a href="../articles/learn.html">Learn</a></nav><a class="nav-cta" href="../pricing/">Premium</a></header><main><section class="scene scene-dark"><div class="howto-hero"><p class="kicker">Practical setup library</p><h1>How to run local and agentic AI with control.</h1><p class="subhead">Source-linked setup guides for runtimes, agent gateways, browser interfaces, and the security boundaries between them.</p></div></section><section class="scene scene-light"><div class="content-hub-grid">{''.join(cards)}</div></section></main><footer class="footer"><span>© 2026 AIToolsEssentials</span><a href="../methodology/">Methodology</a><a href="../legal/privacy.html">Privacy</a><a href="../legal/terms.html">Terms</a></footer></body></html>'''
    (out/'index.html').write_text(hub); return len(GUIDES)+1
if __name__=='__main__': print(generate(Path(__file__).resolve().parents[1]))
