#!/usr/bin/env python3
"""Generate the public AIToolsEssentials editorial methodology page."""
from pathlib import Path
import json

DOMAIN = "https://aitoolsessentials.com"

def generate(root: Path, today: str) -> Path:
    schema = json.dumps({"@context":"https://schema.org","@type":"AboutPage","name":"AIToolsEssentials Editorial Methodology","url":f"{DOMAIN}/methodology/","dateModified":today,"publisher":{"@type":"Organization","name":"AIToolsEssentials"}})
    page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="How AIToolsEssentials evaluates AI tools: scoring rubric, source hierarchy, pricing freshness, benchmark policy, affiliate independence, and community evidence rules."><title>Editorial Methodology — How We Evaluate AI Tools | AIToolsEssentials</title><link rel="canonical" href="{DOMAIN}/methodology/"><meta property="og:title" content="Editorial Methodology — AIToolsEssentials"><meta property="og:description" content="Our public rules for AI tool scores, pricing evidence, benchmarks, affiliate links, and community results."><meta property="og:image" content="{DOMAIN}/assets/og-ai-tools.jpg"><link rel="stylesheet" href="/css/styles.css"><link rel="stylesheet" href="/css/share.css"><script type="application/ld+json">{schema}</script></head><body>
<header class="global-nav"><a class="brand" href="/index.html"><span class="brand-glyph">✦</span><span>AIToolsEssentials</span></a><nav class="nav-links"><a href="/tools/index.html">Tools</a><a href="/comparisons/best-ai-tools.html">Best AI tools</a><a href="/categories/">Categories</a><a href="/guides/switch-guides/">Switching</a><a href="/evidence/">Evidence</a><a href="/benchmarks/">Benchmarks</a></nav><a class="nav-cta" href="/premium/">Premium</a></header><main>
<section class="scene scene-dark"><div class="methodology-hero"><p class="kicker">Editorial rules · updated {today}</p><h1>Independent scores need visible rules.</h1><p class="subhead">This is how AIToolsEssentials evaluates tools, handles uncertainty, checks pricing, uses benchmarks, and keeps monetization separate from editorial judgment.</p><p><a class="button button-blue" href="/evidence/">Open evidence ledger</a><a class="button button-dark" href="/legal/corrections.html">Request a correction</a></p></div></section>
<section class="scene scene-light content-hub"><div class="article-shell wide">
<section class="methodology-block"><span class="kicker light">01 · What the score means</span><h2>Scores measure decision fitness, not popularity.</h2><p>Our editorial score is a structured judgment about how well a tool fits its stated job for a defined buyer. A high score does not mean the tool is best for everyone. Every review includes best-fit guidance, trade-offs, and a test-before-paying checklist.</p><div class="methodology-grid"><article class="score-card"><strong>Job fit · 30%</strong><p>Does the tool solve the workflow it claims to solve, at the buyer's likely scale?</p></article><article class="score-card"><strong>Output quality · 25%</strong><p>How useful, controllable, and repeatable are the outputs for the target job?</p></article><article class="score-card"><strong>Workflow depth · 20%</strong><p>Does it support the surrounding process — files, integrations, agents, export, or collaboration?</p></article><article class="score-card"><strong>Value &amp; cost pressure · 15%</strong><p>Does the pricing model make sense at realistic usage, including limits and seat pressure?</p></article><article class="score-card"><strong>Trust &amp; operational fit · 10%</strong><p>Are privacy, rights, availability, and policy details clear enough for the intended buyer?</p></article></div></section>
<section class="methodology-block"><span class="kicker light">02 · Source hierarchy</span><h2>Official sources outrank summaries.</h2><ol class="methodology-list"><li><strong>Primary:</strong> vendor pricing, documentation, terms, privacy, rights, and product announcements.</li><li><strong>Secondary:</strong> reputable benchmark publishers and clearly identified third-party evidence.</li><li><strong>Context:</strong> community reports, labeled as individual experience rather than editorial testing.</li><li><strong>Unknown:</strong> missing information stays marked unresolved; we do not fill gaps with confident-sounding guesses.</li></ol><p><a class="text-link" href="/evidence/">See the source row for every reviewed tool →</a></p></section>
<section class="methodology-block"><span class="kicker light">03 · Freshness rules</span><h2>Fast-changing claims get dates.</h2><div class="methodology-grid"><article class="score-card"><strong>Pricing</strong><p>Official pricing rows show the last checked date. Pricing Watch compares future snapshots and records confirmed differences rather than inventing history.</p></article><article class="score-card"><strong>Models</strong><p>Comparisons name actual shipping model/product versions and checked dates. A vendor lineup change triggers a data update before editorial copy is treated as current.</p></article><article class="score-card"><strong>Benchmarks</strong><p>Benchmark entries retain the exact model, benchmark name, configuration, result, and snapshot date. Missing comparable data is labeled unavailable.</p></article></div></section>
<section class="methodology-block"><span class="kicker light">04 · Monetization independence</span><h2>Affiliate links cannot buy a ranking.</h2><p>Affiliate and sponsored links are labeled and use the required sponsored/nofollow attributes. We only wire tracking URLs issued by a real program. Affiliate availability, commission, or conversion rate does not change an editorial score or placement.</p><p>Where no approved affiliate relationship exists, the page uses the vendor's ordinary official link. Grammarly and Impact-linked programs remain excluded until an approved tracking relationship exists.</p></section>
<section class="methodology-block"><span class="kicker light">05 · Community evidence</span><h2>Experience reports stay labeled.</h2><p>We do not fabricate hands-on results, votes, traffic, or testimonials. Community reports include the tool, plan, task, duration, what worked, what broke, and cost context. Published reports remain attributed as individual experiences and do not silently become editorial test results.</p></section>
<section class="score-card methodology-next"><span>Challenge the record</span><h2>Found a stale claim?</h2><p>Send the URL, the relevant source, and what changed. Corrections are logged and source data is rechecked in the next maintenance run.</p><p><a class="button button-blue" href="/legal/corrections.html">Submit a correction</a><a class="button button-dark" href="/pricing-watch/">Check pricing freshness</a></p></section>
</div></section></main><footer class="footer"><span>© 2026 AIToolsEssentials</span><a href="/evidence/">Evidence ledger</a><a href="/legal/about.html">About</a><a href="/legal/privacy.html">Privacy</a><a href="/legal/terms.html">Terms</a><a href="/legal/corrections.html">Corrections</a><a href="mailto:contact@aitoolsessentials.com">Contact</a></footer><script src="/js/site.js" defer></script><script src="/js/analytics.js" defer></script></body></html>'''
    out=root/'methodology'/'index.html'; out.parent.mkdir(exist_ok=True); out.write_text(page); return out

if __name__ == '__main__':
    from datetime import datetime
    root=Path(__file__).resolve().parent.parent
    print(generate(root, datetime.today().strftime('%Y-%m-%d')))
